### ISSUE TITLE
X13: Error (questionable design choice) in Forecast horizon

### ISSUE THREAD

**Issue by Immurb** [jdemetra/jdemetra-app#173]
Changes in the Forecast horizon have not influence on the shown forecasted values in "Main Results"->"Table"/"Charts" of "Series" (always one year forecast, even with forecast horizon = 0).
 The other time series are in the expected length.

**Comment by palatej** [comment]
The "forecast horizon" defined in the X11 part is in fact independent of the forecast horizon used in the RegArima part. The first one define the number of forecasts (and backcasts in the future) that are used in the computation of the X11 decomposition, while the second one is just related to the RegArima part (pure forecast perspective); it is fixed to 1 year for comparability issues with (for instance) Tramo-Seats. So, it is not a bug, but a (questionable) design choice. I propose to NOT modify this behaviour in JD+ 2.1.0

**Comment by palatej** [comment]
I propose to put in the future release (2.2.0) a new item in the specifications of X13 and Tramo-Seats related to forecasts/backcasts (it is a recurrent request). The forecast horizon should then be removed from the X11 specification and the global forecast/backcast horizons should be used in X11. 
The code (algorithm) is straightforward, but we have to deal with many details (compatibility issues...), so that we can't solve it in a few days.

**Comment by palatej** [comment]
See also #40

**Comment by palatej** [comment]
Work load, including #40: 10 days

**Comment by palatej** [comment]
The forecasts horizon defined in the X11 spec is now used in the main output.
