### ISSUE TITLE
Provider information associated with each series not retrievable in multi-documents

### ISSUE THREAD

**Issue by buerokrata** [jdemetra/jdemetra-app#291]
I did not find a way to retrieve provider information associated with series in a multi-documents project through the user interface. It is possible to check it by visiting the related xml file in the SAProcessing folder, but it would be much more convenient to find it next  to  Input> Specifications and Input>Series, in  an Input>Provider section.
![image](https://cloud.githubusercontent.com/assets/6152628/23271942/bcf9bcc4-f9f9-11e6-89e7-9b8b31ec856d.png)

I also came across of some sort provider related bug. If for some reason (mostly because of a wrongly specified provider) the data section becomes empty in the \<ts\> block of a SAprocessing.xml, there is no way to recover, even by fixing the provider connection in the xml file. Let me know if you need more info to reproduce the bug, perhaps I can provide a corrupt xml file. I observed it with the 2.1 and older releases.

**Comment by charphi** [comment]
For your first problem, I've just merged a PR to improve feedback (see #292).
You can display the properties of a time series by opening the Properties panel (see `Menu>Window>Properties`) and then selecting a ts in any other panel.

You can test it on the latest snapshot of JD+:
https://joinup.ec.europa.eu/nexus/content/repositories/snapshots/eu/europa/ec/joinup/sat/nbdemetra-app/2.2.0-SNAPSHOT/nbdemetra-app-2.2.0-20170224.124051-28.zip 

For your second problem, it might already be fixed by v2.2.0-SNAPSHOT but it would be better to send me the failing xml file (don't forget to remove any confidential information in it).

**Comment by buerokrata** [comment]
I tested the snapshot with the properties, Excellent.
I'll try to put together the test case for the second point next week.

**Comment by charphi** [comment]
Thanks for sending me the test case.
The second problem is now fixed in the latest snapshot.
