### ISSUE TITLE
Bug with the refreshment option "Last outliers"

### ISSUE THREAD

**Issue by ThomasBalcone** [jdemetra/jdemetra-app#311]
Hello,

I noticed that there could be

 a bug whith the refreshment option "last outliers" : 

- I create a workspace with a SAProcessing using the specification X13[RSA5c] and data between [01/1990;10/2016] which come from the file "ipi_nace4_series_brutes.xls". I save the wk as "wk_initial".

- Afterwards, I add two observations for each series in the file "ipi_nace4_series_brutes.xls" for 11/2016 and 12/2016. I open the wk "wk_initial". I refresh the SAProcessing by using the option "last outliers". When I have a look to the "specifications" panel for a series, I see that the detection span for the outliers is "from 11/2015". This doesn't seem correct because each series has two more observations untill 12/2016 and so, the detection span for the outliers should be "from 01/2016", shouldn't it? The corresponding wk is "wk_last_outliers_avec_donnees_12_2016"

Thank you in advance for your answer,

Best regards,
Thomas
[wk_initial.zip](https://github.com/jdemetra/jdemetra-app/files/896383/wk_initial.zip)
[wk_last_outliers_avec_donnees_12_2016.zip](https://github.com/jdemetra/jdemetra-app/files/896382/wk_last_outliers_avec_donnees_12_2016.zip)
[ipi_nace4_series_brutes.zip](https://github.com/jdemetra/jdemetra-app/files/896384/ipi_nace4_series_brutes.zip)

**Comment by ThomasBalcone** [comment]
There is the same bug with the Cruncher.

Best regards,
Thomas

**Comment by palatej** [comment]
Hi Thomas,

The cruncher and the graphical interface use exactly the same libraries. You will always find the same "problems" in the two applications. Now, the meaning of "last outliers" should be more clearly defined. The current idea is that the last outliers are perhaps badly identified, so that we might have to modify them. I think that the current implementation is correct in that way (the period corresponds to the currently identified outliers).
