### ISSUE TITLE
Problem with importing specification

### ISSUE THREAD

**Issue by MariaPetsch** [jdemetra/jdemetra-app#388]
Dear Developers,

We have a problem with importing specification in JD+ version 2.2.0. We tried to saved a specification with national calendar. After we import that specification we find that it didn't contain the national calendar anymore. 

We can see the name of our calendar in the specification, but if click on it, it is disappeared.

Kind regards,
Gábor and Maria from HCSO

**Comment by charphi** [comment]
Your problem seems to come from the import/export feature of JD+.

When you export a specification, it does export the specification but not its "dependencies".
In your case, your national calendar is a dependency of the specification.

To solve your problem, you need to export the calendar and the specification.
Import the calendar first and then the specification.

**Comment by MariaPetsch** [comment]
Hi, thanks for your help. 
Maria
