### ISSUE TITLE
Installer doesn't work on Mac OS 10.15 (Catalina)

### ISSUE THREAD

**Issue by fable** [jdemetra/jdemetra-app#472]
Even with latest JAVA Se installed (13) the installer won't start.

**Comment by charphi** [comment]
macOS Catalina doesn't have Java installed by default and it also enforce security policies.

To install JD+ on macOS Catalina, you need to
1. Download and install [OpenJdk8](https://adoptopenjdk.net/index.html) x64 for macOS: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jre_x64_mac_hotspot_8u232b09.pkg 
2. Run the JD+ installer. You should see a dialog box that tells you the application cannot be launched since it is not signed.
3. Go to `System Preferences>Security & Privacy>General`and click on the button `Open Anyway` in the section ` Allow apps downloaded from`
4. JD+ installer should start again; run it manually if not

**Comment by charphi** [comment]
Related documentation: https://www.oracle.com/technetwork/java/javase/using-jdk-jre-macos-catalina-5781620.html

**Comment by fable** [comment]
Thanks. I installed the Java .pkg in your link but the JDemetra installer opens and closes immediately.
Any other advice ? Is it normal that I can’t find a Java panel in System Preferences as it happened in the past ?

**Comment by charphi** [comment]
You might need to give some authorization to Java.

Open up a terminal and type in : `java -version`
This should trigger a dialog box that grants the file system permission to Java.

**Comment by fable** [comment]
I tried it:

> MacBook:~ fabiofable$ java -version
> java version "13.0.1" 2019-10-15
> Java(TM) SE Runtime Environment (build 13.0.1+9)
> Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

no new pop-up , but the installer keep opening and closing immediately.

**Comment by charphi** [comment]
It seems that your default Java runtime is Java13 which is not currently supported by JD+.
Could you uninstall it?
When this is done, try again the command `java -version` to check if Java8 is the default one.

**Comment by fable** [comment]
I removed the 13 version .jdk and now :

MacBook:~ fabiofable$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
MacBook:~ fabiofable$ 

Is Java 9 supported ? The installer doesn't work yet.

**Comment by charphi** [comment]
Currently only Java8.

**Comment by fable** [comment]
Ok, now the installer and the program work correctly. Unfortunatelly my work VPN-connection  (Checkpoint ) doesn't work anymore ;-) but at least I know what's the issue.
Thank you !

**Comment by charphi** [comment]
You are welcome :)
