### ISSUE TITLE
Refresh "Current Adjustement (AO Approach)"

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdemetra-app#521]
1.) The results in the UI are different if you use the refresh from the menu for the whole multi-document or for a selection of SA-Items. In the second case in the specification for the Intervention for the last value of the series is not listed and the Intervention (AO....) is also missing in the Pre-Processing results. 

2.) The intervention is always set to the last value of the series, not taken into account the Span of the Series. Is this the intended solution?

Version 2.2.3 RC-1

**Comment by palatej** [comment]
Hi Christiane, 

Thank you for your remarks. 
1) OK. I correct the bug in RC2.
2) Yes. It is by design. The goal is indeed to add AOs when we know a priori that the series contains strange figures for the new periods. The use or not of a span is not relevant in that case (moreover, it would be unmanageable: how to react to the different kinds of spans (last, excluding, to...). From my point of view, it is clear that such a revision policy should be used with parsimony: it just means: don't use the last figures...
