### ISSUE TITLE
Release v2.2.5 requires Java 17 on Windows

### ISSUE THREAD

**Issue by m20l22** [jdemetra/jdemetra-app#912]
Hello all! I have installed JDemetra+ v2.2.5 (jdemetra-2.2.5-setup-windows.exe) on Windows with Java 8. Opening JDemetra+ stops with an error message asking for Java 17. Is it intentional? I was assuming Java 8 should be enough for running JDemetra+ version 2.X.X.

![image](https://github.com/user-attachments/assets/09b752df-381e-483b-999b-d4c26f348551)

P.S. I have installed Java 21 and JDemetra+ v2.2.5 works now.

**Comment by charphi** [comment]
You are right: JDemetra+ v2.2.5 requires at least Java 17.
This was not intended and is the result of a unknown-to-us change in the NetBeans Platform used to create the GUI.
(see https://github.com/apache/netbeans/commit/7e625c44a472d45a513ada1e6ef7526c6d3a7720) 

We won't change this behavior since it is a minor inconvenience but we will update the documentation.

Java requirement summary in JDemetra+ v2.2.5:

| Name | Purpose | Java version |
| --- | --- | --- |
| JDemetra+ | Desktop app |  17 |
| Jwsacruncher | CLI tool |  8 |
| *.jar | Development libraries |  8 |

**Comment by charphi** [comment]
I've updated the CHANGELOG (https://github.com/jdemetra/jdemetra-app/commit/2535f931e17cd0f3e8c7c69b684b8d6cde1e0ab7)

Hi @annasmyk, could you update the official documentation ?
